Repository AalianKhan/mushroom-strategy, pull requests merged in 2025-03, with the labels that each got.

#164 Add scene domain and associated tap-action
  src/Helper.ts
  src/cards/SceneCard.ts
  src/configurationDefaults.ts
  src/translations/en.json
  src/translations/nl.json
  src/views/AbstractView.ts
  src/views/SceneView.ts
Labels: enhancement, Needs Feedback, In Progress

#176 Add German translation
  src/localize.ts
  src/translations/de.json
Labels: enhancement, In Progress

#179 Translation to Spanish Language
  src/localize.ts
  src/translations/es.json
Labels: enhancement

#153 Add capability to filter diagnostic entities
  src/Helper.ts
  src/configurationDefaults.ts
  src/mushroom-strategy.ts
  src/types/strategy/generic.ts
  src/utillties/filters.ts
  src/views/AbstractView.ts
  src/views/HomeView.ts
Labels: enhancement, Needs Feedback, In Progress
